import Head from 'next/head'
import { Navbar } from '../NavBar'
import styles from './Mainlayout.module.css'

export const Mainlayout = ({ children }) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />
    
          <main className={styles.main}>

            { children }
    
          </main>
    
        </div>
      )
}